# Generated by Django 4.2.7 on 2023-11-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user')),
            ],
        ),
    ]
